apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guardian-hpa
  namespace: guardian-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: get-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30