apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: guardian-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-1:721699489018:secret:rds!db-2348f13b-a0a1-4d55-b7ef-7afd79ed5195-E8bXjr"
        jmesPath: 
            - path: username
              objectAlias: dbusername
            - path: password
              objectAlias: dbpassword



# secret_arn = "arn:aws:secretsmanager:eu-west-1:721699489018:secret:rds!db-8bb1cb13-25ef-4d65-844a-dd3666087bec-L1tgbB"